import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Plus_Jakarta_Sans } from "next/font/google";

import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
	variable: "--font-plus-jakarta-sans",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-BR">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${plusJakartaSans.variable} antialiased flex flex-col items-center justify-center w-screen max-w-screen min-h-screen`}
			>
				{children}
				<Toaster
					toastOptions={{
						duration: 4000,
						style: {
							fontFamily: "var(--font-plus-jakarta-sans)",
							fontSize: "14px",
							fontWeight: "400",
							lineHeight: "20px",
							backgroundColor: "var(--popover)",
							color: "var(--primary)",
							borderColor: "var(--ring)",
							borderWidth: "1px",
							borderStyle: "solid",
							borderRadius: "4px",
							padding: "16px",
							boxShadow: "0px 4px 10px rgba(0, 0, 0, 0.2)",
							transition: "all 0.5s ease-in-out",
						},
					}}
					position="bottom-center"
					richColors
					theme="dark"
				/>
			</body>
		</html>
	);
}
